name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Fetch Secrets and Add in Environment
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          APP_ID: ${{ secrets.APP_ID }}
        run: echo "Base Url = $BASE_URL App Id = $APP_ID"

      - name: Add local.properties file
        run: echo -e "base_url= $BASE_URL \n app_id= $APP_ID" > ./local.properties

      - name: Generate Lint Report
        run: ./gradlew lintDebug

      - name: Upload Lint report
        uses: actions/upload-artifact@v2
        with:
          name: lint.html
          path: app/build/reports/lint-results-debug.html